#include <fsi/util/status.h>

const char *parser_status_lookup[22] =
    {
        "PARSER_STATUS_OK",
        "PARSER_STATUS_END_REPL",
        "PARSER_STATUS_TOKEN_TOO_LONG",
        "PARSER_STATUS_INTERPRETED_OVERFLOW",
        "PARSER_STATUS_COMPILED_OVERFLOW",
        "PARSER_STATUS_INVALID_BASE",
        "PARSER_STATUS_INVALID_BASE10",
        "PARSER_STATUS_INVALID_BASE16",
        "PARSER_STATUS_NESTED_COMPILATION_MODE",
        "PARSER_STATUS_NOT_IN_COMPILATION_MODE",
        "PARSER_STATUS_NOT_IN_INTERPRETATION_MODE",
        "PARSER_STATUS_LOOKUP_OVERFLOW",
        "PARSER_STATUS_PENDING_DEFINITION",
        "PARSER_STATUS_PARSER_CONTROL_STACK_OVERFLOW",
        "PARSER_STATUS_PARSER_CONTROL_STACK_UNDERFLOW",
        "PARSER_STATUS_PARSER_CONTROL_STACK_MISMATCH",
        "PARSER_STATUS_INCOMPLETE_STRING",
        "PARSER_STATUS_LITERAL_OVERFLOW",
        "PARSER_STATUS_COUNTED_STRING_OVERFLOW",
        "PARSER_STATUS_MODULE_NAME_OVERFLOW",
        "PARSER_STATUS_MOD_OVERFLOW",
        "PARSER_STATUS_MOD_LOAD"
    };

const char *vm_status_lookup[12] =
    {
        "VM_STATUS_OK",
        "VM_STATUS_OUT_OF_MEMORY",
        "VM_STATUS_DATA_STACK_OVERFLOW",
        "VM_STATUS_DATA_STACK_UNDERFLOW",
        "VM_STATUS_INVALID_BASE",
        "VM_STATUS_CONTROL_STACK_OVERFLOW",
        "VM_STATUS_CONTROL_STACK_UNDERFLOW",
        "VM_STATUS_INVALID_RETURN_ADDRESS",
        "VM_STATUS_INVALID_MEMORY_ADDRESS",
        "VM_STATUS_INVALID_MEMORY_ALLOCATION",
        "VM_STATUS_FLOAT_STACK_OVERFLOW",
        "VM_STATUS_FLOAT_STACK_UNDERFLOW"
    };
