#ifndef UTIL_STATUS_H_
#define UTIL_STATUS_H_

#define PARSER_STATUS_OK 0
#define PARSER_STATUS_END_REPL 1
#define PARSER_STATUS_TOKEN_TOO_LONG 2
#define PARSER_STATUS_INTERPRETED_OVERFLOW 3
#define PARSER_STATUS_COMPILED_OVERFLOW 4
#define PARSER_STATUS_INVALID_BASE 5
#define PARSER_STATUS_INVALID_BASE10 6
#define PARSER_STATUS_INVALID_BASE16 7
#define PARSER_STATUS_NESTED_COMPILATION_MODE 8
#define PARSER_STATUS_NOT_IN_COMPILATION_MODE 9
#define PARSER_STATUS_LOOKUP_OVERFLOW 10
#define PARSER_STATUS_PENDING_DEFINITION 11
#define PARSER_STATUS_PARSER_CONTROL_STACK_OVERFLOW 12
#define PARSER_STATUS_PARSER_CONTROL_STACK_UNDERFLOW 13
#define PARSER_STATUS_PARSER_CONTROL_STACK_MISMATCH 14

#define VM_STATUS_OK 0
#define VM_STATUS_DATA_STACK_OVERFLOW 1
#define VM_STATUS_DATA_STACK_UNDERFLOW 2
#define VM_STATUS_INVALID_BASE 3
#define VM_STATUS_CONTROL_STACK_OVERFLOW 4
#define VM_STATUS_CONTROL_STACK_UNDERFLOW 5
#define VM_STATUS_INVALID_RETURN_ADDRESS 6
#define VM_STATUS_INVALID_MEMORY_ADDRESS 7

extern const char *parser_status_lookup[15];
extern const char *vm_status_lookup[8];

#endif
