#ifndef FSHP_FSHP_H_
#define FSHP_FSHP_H_

#include <fsi/vm/vm.h>
#include <fsi/parser/parser.h>
#include <fsi/util/parser_util.h>

typedef enum FSHPStatus {
    FSHP_STATUS_OK,
    FSHP_STATUS_FILE_OPEN,
    FSHP_STATUS_OUT_OF_MEMORY,
    FSHP_PARSER_STATUS_END_REPL,
    FSHP_PARSER_STATUS_OUT_OF_MEMORY,
    FSHP_PARSER_STATUS_INTERPRETED_OVERFLOW,
    FSHP_PARSER_STATUS_COMPILED_OVERFLOW,
    FSHP_PARSER_STATUS_INVALID_BASE,
    FSHP_PARSER_STATUS_INVALID_BASE10,
    FSHP_PARSER_STATUS_INVALID_BASE16,
    FSHP_PARSER_STATUS_NESTED_COMPILATION_MODE,
    FSHP_PARSER_STATUS_NOT_IN_COMPILATION_MODE,
    FSHP_PARSER_STATUS_NOT_IN_INTERPRETATION_MODE,
    FSHP_PARSER_STATUS_LOOKUP_OVERFLOW,
    FSHP_PARSER_STATUS_PENDING_DEFINITION,
    FSHP_PARSER_STATUS_PARSER_CONTROL_STACK_OVERFLOW,
    FSHP_PARSER_STATUS_PARSER_CONTROL_STACK_UNDERFLOW,
    FSHP_PARSER_STATUS_PARSER_CONTROL_STACK_MISMATCH,
    FSHP_PARSER_STATUS_INCOMPLETE_STRING,
    FSHP_PARSER_STATUS_LITERAL_OVERFLOW,
    FSHP_PARSER_STATUS_COUNTED_STRING_OVERFLOW,
    FSHP_PARSER_STATUS_MODULE_NAME_OVERFLOW,
    FSHP_PARSER_STATUS_MOD_OVERFLOW,
    FSHP_PARSER_STATUS_MOD_LOAD,
    FSHP_VM_STATUS_OUT_OF_MEMORY,
    FSHP_VM_STATUS_DATA_STACK_OVERFLOW,
    FSHP_VM_STATUS_DATA_STACK_UNDERFLOW,
    FSHP_VM_STATUS_INVALID_BASE,
    FSHP_VM_STATUS_CONTROL_STACK_OVERFLOW,
    FSHP_VM_STATUS_CONTROL_STACK_UNDERFLOW,
    FSHP_VM_STATUS_INVALID_RETURN_ADDRESS,
    FSHP_VM_STATUS_INVALID_MEMORY_ADDRESS,
    FSHP_VM_STATUS_INVALID_MEMORY_ALLOCATION,
    FSHP_VM_STATUS_FLOAT_STACK_OVERFLOW,
    FSHP_VM_STATUS_FLOAT_STACK_UNDERFLOW
} FSHPStatus;

extern const char *fshp_status_lookup[35];

FSHPStatus fshp_process_file(
    char *fn, ForthVM *vm, ForthParser *parser, String *buf);

#endif
